// <auto-generated />
using System;
using ListaPrzebojow.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ListaPrzebojowContext))]
    [Migration("20230329201224_test1")]
    partial class test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumID"));

                    b.Property<int?>("ChartAlbumowID")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PiosenkaID")
                        .HasColumnType("int");

                    b.HasKey("AlbumID");

                    b.HasIndex("ChartAlbumowID");

                    b.HasIndex("PiosenkaID");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("DAL.Artysta", b =>
                {
                    b.Property<int>("ArtystaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtystaID"));

                    b.Property<string>("Pseudonim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SluchaczeWMiesiacu")
                        .HasColumnType("int");

                    b.HasKey("ArtystaID");

                    b.ToTable("Artysta");

                    b.HasData(
                        new
                        {
                            ArtystaID = 1,
                            Pseudonim = "Artysta 1",
                            SluchaczeWMiesiacu = 1000
                        },
                        new
                        {
                            ArtystaID = 2,
                            Pseudonim = "Artysta 2",
                            SluchaczeWMiesiacu = 500
                        });
                });

            modelBuilder.Entity("DAL.ArtystaAlbum", b =>
                {
                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("ArtystaID")
                        .HasColumnType("int");

                    b.HasKey("AlbumID", "ArtystaID");

                    b.HasIndex("ArtystaID");

                    b.ToTable("ArtystaAlbum");
                });

            modelBuilder.Entity("DAL.Chart", b =>
                {
                    b.Property<int>("ChartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChartID"));

                    b.Property<int>("ChartAlbumowID")
                        .HasColumnType("int");

                    b.HasKey("ChartID");

                    b.ToTable("Chart");
                });

            modelBuilder.Entity("DAL.ChartAlbumow", b =>
                {
                    b.Property<int>("ChartAlbumowID")
                        .HasColumnType("int");

                    b.Property<int>("ChartID")
                        .HasColumnType("int");

                    b.HasKey("ChartAlbumowID");

                    b.ToTable("ChartAlbumow");
                });

            modelBuilder.Entity("DAL.ChartPiosenek", b =>
                {
                    b.Property<int>("ChartPiosenekID")
                        .HasColumnType("int");

                    b.Property<int>("ChartID")
                        .HasColumnType("int");

                    b.HasKey("ChartPiosenekID");

                    b.ToTable("ChartPiosenek");
                });

            modelBuilder.Entity("DAL.Piosenka", b =>
                {
                    b.Property<int>("PiosenkaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PiosenkaID"));

                    b.Property<int?>("ChartPiosenekID")
                        .HasColumnType("int");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IleOdsluchan")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaylistaID")
                        .HasColumnType("int");

                    b.HasKey("PiosenkaID");

                    b.HasIndex("ChartPiosenekID");

                    b.HasIndex("PlaylistaID");

                    b.ToTable("Piosenka");

                    b.HasData(
                        new
                        {
                            PiosenkaID = 1,
                            Gatunek = "Rock",
                            IleOdsluchan = 100,
                            Nazwa = "Piosenka 1"
                        },
                        new
                        {
                            PiosenkaID = 2,
                            Gatunek = "Pop",
                            IleOdsluchan = 50,
                            Nazwa = "Piosenka 2"
                        });
                });

            modelBuilder.Entity("DAL.PiosenkaArtysta", b =>
                {
                    b.Property<int>("PiosenkaID")
                        .HasColumnType("int");

                    b.Property<int>("ArtystaID")
                        .HasColumnType("int");

                    b.HasKey("PiosenkaID", "ArtystaID");

                    b.HasIndex("ArtystaID");

                    b.ToTable("PiosenkaArtysta");

                    b.HasData(
                        new
                        {
                            PiosenkaID = 1,
                            ArtystaID = 1
                        },
                        new
                        {
                            PiosenkaID = 2,
                            ArtystaID = 2
                        });
                });

            modelBuilder.Entity("DAL.PiosenkaNaCharcie", b =>
                {
                    b.Property<int>("PiosenkaID")
                        .HasColumnType("int");

                    b.Property<int>("ChartPiosenekID")
                        .HasColumnType("int");

                    b.Property<int>("PozycjaPiosenki")
                        .HasColumnType("int");

                    b.HasKey("PiosenkaID", "ChartPiosenekID");

                    b.HasIndex("ChartPiosenekID");

                    b.ToTable("PiosenkaNaCharcie");
                });

            modelBuilder.Entity("DAL.Playlista", b =>
                {
                    b.Property<int>("PlaylistaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaylistaID"));

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaylistaID");

                    b.ToTable("Playlista");
                });

            modelBuilder.Entity("ListaPrzebojow.DAL.AlbumNaCharcie", b =>
                {
                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("ChartAlbumowID")
                        .HasColumnType("int");

                    b.HasKey("AlbumID", "ChartAlbumowID");

                    b.HasIndex("ChartAlbumowID");

                    b.ToTable("AlbumNaCharcie");
                });

            modelBuilder.Entity("ListaPrzebojow.DAL.PiosenkaNaPlayliscie", b =>
                {
                    b.Property<int>("PiosenkaID")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistaID")
                        .HasColumnType("int");

                    b.HasKey("PiosenkaID", "PlaylistaID");

                    b.HasIndex("PlaylistaID");

                    b.ToTable("PiosenkaNaPlayliscie");
                });

            modelBuilder.Entity("DAL.Album", b =>
                {
                    b.HasOne("DAL.ChartAlbumow", null)
                        .WithMany("albumy")
                        .HasForeignKey("ChartAlbumowID");

                    b.HasOne("DAL.Piosenka", null)
                        .WithMany("AlbumCol")
                        .HasForeignKey("PiosenkaID");
                });

            modelBuilder.Entity("DAL.ArtystaAlbum", b =>
                {
                    b.HasOne("DAL.Album", "album")
                        .WithMany("artystaAlbumCol")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Artysta", "artysta")
                        .WithMany("artystaAlbumCol")
                        .HasForeignKey("ArtystaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("album");

                    b.Navigation("artysta");
                });

            modelBuilder.Entity("DAL.ChartAlbumow", b =>
                {
                    b.HasOne("DAL.Chart", "chart")
                        .WithOne("chartAlbumow")
                        .HasForeignKey("DAL.ChartAlbumow", "ChartAlbumowID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("chart");
                });

            modelBuilder.Entity("DAL.ChartPiosenek", b =>
                {
                    b.HasOne("DAL.Chart", "chart")
                        .WithOne("chartPiosenek")
                        .HasForeignKey("DAL.ChartPiosenek", "ChartPiosenekID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("chart");
                });

            modelBuilder.Entity("DAL.Piosenka", b =>
                {
                    b.HasOne("DAL.ChartPiosenek", null)
                        .WithMany("piosenki")
                        .HasForeignKey("ChartPiosenekID");

                    b.HasOne("DAL.Playlista", null)
                        .WithMany("piosenkaCol")
                        .HasForeignKey("PlaylistaID");
                });

            modelBuilder.Entity("DAL.PiosenkaArtysta", b =>
                {
                    b.HasOne("DAL.Artysta", "artysta")
                        .WithMany("piosenkaArtystaCol")
                        .HasForeignKey("ArtystaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Piosenka", "piosenka")
                        .WithMany("piosenkaArtystaCol")
                        .HasForeignKey("PiosenkaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("artysta");

                    b.Navigation("piosenka");
                });

            modelBuilder.Entity("DAL.PiosenkaNaCharcie", b =>
                {
                    b.HasOne("DAL.ChartPiosenek", "chartPiosenek")
                        .WithMany("PiosenkaNaCharcieCol")
                        .HasForeignKey("ChartPiosenekID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Piosenka", "piosenka")
                        .WithMany("PiosenkaNaCharcieCol")
                        .HasForeignKey("PiosenkaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("chartPiosenek");

                    b.Navigation("piosenka");
                });

            modelBuilder.Entity("ListaPrzebojow.DAL.AlbumNaCharcie", b =>
                {
                    b.HasOne("DAL.Album", "album")
                        .WithMany("AlbumNaCharcieCol")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.ChartAlbumow", "chartAlbumow")
                        .WithMany("AlbumNaCharcieCol")
                        .HasForeignKey("ChartAlbumowID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("album");

                    b.Navigation("chartAlbumow");
                });

            modelBuilder.Entity("ListaPrzebojow.DAL.PiosenkaNaPlayliscie", b =>
                {
                    b.HasOne("DAL.Piosenka", "piosenka")
                        .WithMany("PiosenkaNaPlayliscieCol")
                        .HasForeignKey("PiosenkaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Playlista", "playlista")
                        .WithMany("PiosenkaNaPlayliscieCol")
                        .HasForeignKey("PlaylistaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("piosenka");

                    b.Navigation("playlista");
                });

            modelBuilder.Entity("DAL.Album", b =>
                {
                    b.Navigation("AlbumNaCharcieCol");

                    b.Navigation("artystaAlbumCol");
                });

            modelBuilder.Entity("DAL.Artysta", b =>
                {
                    b.Navigation("artystaAlbumCol");

                    b.Navigation("piosenkaArtystaCol");
                });

            modelBuilder.Entity("DAL.Chart", b =>
                {
                    b.Navigation("chartAlbumow")
                        .IsRequired();

                    b.Navigation("chartPiosenek")
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.ChartAlbumow", b =>
                {
                    b.Navigation("AlbumNaCharcieCol");

                    b.Navigation("albumy");
                });

            modelBuilder.Entity("DAL.ChartPiosenek", b =>
                {
                    b.Navigation("PiosenkaNaCharcieCol");

                    b.Navigation("piosenki");
                });

            modelBuilder.Entity("DAL.Piosenka", b =>
                {
                    b.Navigation("AlbumCol");

                    b.Navigation("PiosenkaNaCharcieCol");

                    b.Navigation("PiosenkaNaPlayliscieCol");

                    b.Navigation("piosenkaArtystaCol");
                });

            modelBuilder.Entity("DAL.Playlista", b =>
                {
                    b.Navigation("PiosenkaNaPlayliscieCol");

                    b.Navigation("piosenkaCol");
                });
#pragma warning restore 612, 618
        }
    }
}
