// <auto-generated />
using System;
using ListaPrzebojow.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ListaPrzebojowContext))]
    partial class ListaPrzebojowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumID"));

                    b.Property<int?>("ChartAlbumowID")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlbumID");

                    b.HasIndex("ChartAlbumowID");

                    b.ToTable("Album");

                    b.HasData(
                        new
                        {
                            AlbumID = 1,
                            Nazwa = "Her Loss"
                        },
                        new
                        {
                            AlbumID = 2,
                            Nazwa = "beerbongs & bentleys"
                        },
                        new
                        {
                            AlbumID = 3,
                            Nazwa = "Queen"
                        },
                        new
                        {
                            AlbumID = 4,
                            Nazwa = "Chromatica"
                        },
                        new
                        {
                            AlbumID = 5,
                            Nazwa = "thank u, next"
                        });
                });

            modelBuilder.Entity("DAL.Artysta", b =>
                {
                    b.Property<int>("ArtystaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtystaID"));

                    b.Property<string>("Pseudonim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SluchaczeWMiesiacu")
                        .HasColumnType("int");

                    b.HasKey("ArtystaID");

                    b.ToTable("Artysta");

                    b.HasData(
                        new
                        {
                            ArtystaID = 1,
                            Pseudonim = "Drake",
                            SluchaczeWMiesiacu = 1000
                        },
                        new
                        {
                            ArtystaID = 2,
                            Pseudonim = "21 Savage",
                            SluchaczeWMiesiacu = 500
                        },
                        new
                        {
                            ArtystaID = 3,
                            Pseudonim = "Post Malone",
                            SluchaczeWMiesiacu = 579841
                        },
                        new
                        {
                            ArtystaID = 4,
                            Pseudonim = "Nicki Minaj",
                            SluchaczeWMiesiacu = 676543
                        },
                        new
                        {
                            ArtystaID = 5,
                            Pseudonim = "Lil Wayne",
                            SluchaczeWMiesiacu = 692834
                        },
                        new
                        {
                            ArtystaID = 6,
                            Pseudonim = "Lady Gaga",
                            SluchaczeWMiesiacu = 44355321
                        },
                        new
                        {
                            ArtystaID = 7,
                            Pseudonim = "Ariana Grande",
                            SluchaczeWMiesiacu = 78843849
                        });
                });

            modelBuilder.Entity("DAL.ArtystaAlbum", b =>
                {
                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("ArtystaID")
                        .HasColumnType("int");

                    b.HasKey("AlbumID", "ArtystaID");

                    b.HasIndex("ArtystaID");

                    b.ToTable("ArtystaAlbum");

                    b.HasData(
                        new
                        {
                            AlbumID = 1,
                            ArtystaID = 1
                        },
                        new
                        {
                            AlbumID = 2,
                            ArtystaID = 3
                        },
                        new
                        {
                            AlbumID = 3,
                            ArtystaID = 4
                        },
                        new
                        {
                            AlbumID = 4,
                            ArtystaID = 6
                        },
                        new
                        {
                            AlbumID = 5,
                            ArtystaID = 7
                        });
                });

            modelBuilder.Entity("DAL.Chart", b =>
                {
                    b.Property<int>("ChartID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChartID"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChartID");

                    b.ToTable("Chart");

                    b.HasData(
                        new
                        {
                            ChartID = 1,
                            Nazwa = "top 10 pop"
                        },
                        new
                        {
                            ChartID = 2,
                            Nazwa = "top"
                        });
                });

            modelBuilder.Entity("DAL.ChartAlbumow", b =>
                {
                    b.Property<int>("ChartAlbumowID")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChartAlbumowID");

                    b.ToTable("ChartAlbumow");

                    b.HasData(
                        new
                        {
                            ChartAlbumowID = 1,
                            Nazwa = "top 10 miesiaca"
                        },
                        new
                        {
                            ChartAlbumowID = 2,
                            Nazwa = "top pop"
                        });
                });

            modelBuilder.Entity("DAL.ChartPiosenek", b =>
                {
                    b.Property<int>("ChartPiosenekID")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChartPiosenekID");

                    b.ToTable("ChartPiosenek");

                    b.HasData(
                        new
                        {
                            ChartPiosenekID = 1,
                            Nazwa = "top 10 miesiaca"
                        },
                        new
                        {
                            ChartPiosenekID = 2,
                            Nazwa = "top 10 pop"
                        });
                });

            modelBuilder.Entity("DAL.Piosenka", b =>
                {
                    b.Property<int>("PiosenkaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PiosenkaID"));

                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int?>("ChartPiosenekID")
                        .HasColumnType("int");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IleOdsluchan")
                        .HasColumnType("int");

                    b.Property<int>("IleOdsluchanTydzien")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaylistaID")
                        .HasColumnType("int");

                    b.HasKey("PiosenkaID");

                    b.HasIndex("AlbumID");

                    b.HasIndex("ChartPiosenekID");

                    b.HasIndex("PlaylistaID");

                    b.ToTable("Piosenka");

                    b.HasData(
                        new
                        {
                            PiosenkaID = 1,
                            AlbumID = 1,
                            Gatunek = "Rap",
                            IleOdsluchan = 430030716,
                            IleOdsluchanTydzien = 107507679,
                            Nazwa = "Rich Flex"
                        },
                        new
                        {
                            PiosenkaID = 2,
                            AlbumID = 1,
                            Gatunek = "Rap",
                            IleOdsluchan = 128496585,
                            IleOdsluchanTydzien = 32124146,
                            Nazwa = "Major Distribution"
                        },
                        new
                        {
                            PiosenkaID = 3,
                            AlbumID = 1,
                            Gatunek = "Rap",
                            IleOdsluchan = 128696575,
                            IleOdsluchanTydzien = 32174143,
                            Nazwa = "On BS"
                        },
                        new
                        {
                            PiosenkaID = 4,
                            AlbumID = 1,
                            Gatunek = "Rap",
                            IleOdsluchan = 762226574,
                            IleOdsluchanTydzien = 19055664,
                            Nazwa = "BackOutsideBoyz"
                        },
                        new
                        {
                            PiosenkaID = 5,
                            AlbumID = 1,
                            Gatunek = "Rap",
                            IleOdsluchan = 87005583,
                            IleOdsluchanTydzien = 19055664,
                            Nazwa = "Privileged Rappers"
                        },
                        new
                        {
                            PiosenkaID = 6,
                            AlbumID = 2,
                            Gatunek = "Rap",
                            IleOdsluchan = 873355833,
                            IleOdsluchanTydzien = 218338958,
                            Nazwa = "rockstar"
                        },
                        new
                        {
                            PiosenkaID = 7,
                            AlbumID = 2,
                            Gatunek = "Rap",
                            IleOdsluchan = 919573559,
                            IleOdsluchanTydzien = 229893389,
                            Nazwa = "Candy Paint"
                        },
                        new
                        {
                            PiosenkaID = 8,
                            AlbumID = 2,
                            Gatunek = "Rap",
                            IleOdsluchan = 944573559,
                            IleOdsluchanTydzien = 236143389,
                            Nazwa = "Otherside"
                        },
                        new
                        {
                            PiosenkaID = 9,
                            AlbumID = 2,
                            Gatunek = "Rap",
                            IleOdsluchan = 396452492,
                            IleOdsluchanTydzien = 99113123,
                            Nazwa = "Ball For Me"
                        },
                        new
                        {
                            PiosenkaID = 10,
                            AlbumID = 2,
                            Gatunek = "Rap",
                            IleOdsluchan = 356452492,
                            IleOdsluchanTydzien = 89113123,
                            Nazwa = "Stay"
                        },
                        new
                        {
                            PiosenkaID = 11,
                            AlbumID = 3,
                            Gatunek = "Rap",
                            IleOdsluchan = 155198494,
                            IleOdsluchanTydzien = 38799623,
                            Nazwa = "Barbie Dreams"
                        },
                        new
                        {
                            PiosenkaID = 12,
                            AlbumID = 3,
                            Gatunek = "Rap",
                            IleOdsluchan = 919573559,
                            IleOdsluchanTydzien = 229893389,
                            Nazwa = "Chun-Li"
                        },
                        new
                        {
                            PiosenkaID = 13,
                            AlbumID = 3,
                            Gatunek = "Rap",
                            IleOdsluchan = 934573559,
                            IleOdsluchanTydzien = 233643389,
                            Nazwa = "Good Form"
                        },
                        new
                        {
                            PiosenkaID = 14,
                            AlbumID = 3,
                            Gatunek = "Rap",
                            IleOdsluchan = 396452492,
                            IleOdsluchanTydzien = 99113123,
                            Nazwa = "Miami"
                        },
                        new
                        {
                            PiosenkaID = 15,
                            AlbumID = 3,
                            Gatunek = "Rap",
                            IleOdsluchan = 356452492,
                            IleOdsluchanTydzien = 89113123,
                            Nazwa = "Run & Hide"
                        },
                        new
                        {
                            PiosenkaID = 16,
                            AlbumID = 4,
                            Gatunek = "Pop",
                            IleOdsluchan = 356893192,
                            IleOdsluchanTydzien = 89223298,
                            Nazwa = "Alice"
                        },
                        new
                        {
                            PiosenkaID = 17,
                            AlbumID = 4,
                            Gatunek = "Pop",
                            IleOdsluchan = 354553192,
                            IleOdsluchanTydzien = 88638298,
                            Nazwa = "Stupid Love"
                        },
                        new
                        {
                            PiosenkaID = 18,
                            AlbumID = 4,
                            Gatunek = "Pop",
                            IleOdsluchan = 544553192,
                            IleOdsluchanTydzien = 136138298,
                            Nazwa = "Rain On Me"
                        },
                        new
                        {
                            PiosenkaID = 19,
                            AlbumID = 4,
                            Gatunek = "Pop",
                            IleOdsluchan = 234553192,
                            IleOdsluchanTydzien = 58638298,
                            Nazwa = "Replay"
                        },
                        new
                        {
                            PiosenkaID = 20,
                            AlbumID = 4,
                            Gatunek = "Pop",
                            IleOdsluchan = 22153192,
                            IleOdsluchanTydzien = 5538298,
                            Nazwa = "Enigma"
                        },
                        new
                        {
                            PiosenkaID = 21,
                            AlbumID = 5,
                            Gatunek = "Pop",
                            IleOdsluchan = 382870556,
                            IleOdsluchanTydzien = 95717639,
                            Nazwa = "imagine"
                        },
                        new
                        {
                            PiosenkaID = 22,
                            AlbumID = 5,
                            Gatunek = "Pop",
                            IleOdsluchan = 330118734,
                            IleOdsluchanTydzien = 82529683,
                            Nazwa = "needy"
                        },
                        new
                        {
                            PiosenkaID = 23,
                            AlbumID = 5,
                            Gatunek = "Pop",
                            IleOdsluchan = 289306849,
                            IleOdsluchanTydzien = 72326712,
                            Nazwa = "NASA"
                        },
                        new
                        {
                            PiosenkaID = 24,
                            AlbumID = 5,
                            Gatunek = "Pop",
                            IleOdsluchan = 260845535,
                            IleOdsluchanTydzien = 65211383,
                            Nazwa = "bloodline"
                        },
                        new
                        {
                            PiosenkaID = 25,
                            AlbumID = 5,
                            Gatunek = "Pop",
                            IleOdsluchan = 205119049,
                            IleOdsluchanTydzien = 51279762,
                            Nazwa = "fake smile"
                        });
                });

            modelBuilder.Entity("DAL.PiosenkaArtysta", b =>
                {
                    b.Property<int>("PiosenkaID")
                        .HasColumnType("int");

                    b.Property<int>("ArtystaID")
                        .HasColumnType("int");

                    b.HasKey("PiosenkaID", "ArtystaID");

                    b.HasIndex("ArtystaID");

                    b.ToTable("PiosenkaArtysta");

                    b.HasData(
                        new
                        {
                            PiosenkaID = 1,
                            ArtystaID = 1
                        },
                        new
                        {
                            PiosenkaID = 1,
                            ArtystaID = 2
                        },
                        new
                        {
                            PiosenkaID = 2,
                            ArtystaID = 2
                        },
                        new
                        {
                            PiosenkaID = 3,
                            ArtystaID = 1
                        },
                        new
                        {
                            PiosenkaID = 3,
                            ArtystaID = 2
                        },
                        new
                        {
                            PiosenkaID = 4,
                            ArtystaID = 1
                        },
                        new
                        {
                            PiosenkaID = 5,
                            ArtystaID = 1
                        },
                        new
                        {
                            PiosenkaID = 5,
                            ArtystaID = 2
                        },
                        new
                        {
                            PiosenkaID = 6,
                            ArtystaID = 2
                        },
                        new
                        {
                            PiosenkaID = 6,
                            ArtystaID = 3
                        },
                        new
                        {
                            PiosenkaID = 7,
                            ArtystaID = 3
                        },
                        new
                        {
                            PiosenkaID = 8,
                            ArtystaID = 3
                        },
                        new
                        {
                            PiosenkaID = 9,
                            ArtystaID = 3
                        },
                        new
                        {
                            PiosenkaID = 9,
                            ArtystaID = 4
                        },
                        new
                        {
                            PiosenkaID = 10,
                            ArtystaID = 3
                        },
                        new
                        {
                            PiosenkaID = 11,
                            ArtystaID = 4
                        },
                        new
                        {
                            PiosenkaID = 12,
                            ArtystaID = 4
                        },
                        new
                        {
                            PiosenkaID = 13,
                            ArtystaID = 4
                        },
                        new
                        {
                            PiosenkaID = 13,
                            ArtystaID = 5
                        },
                        new
                        {
                            PiosenkaID = 14,
                            ArtystaID = 4
                        },
                        new
                        {
                            PiosenkaID = 15,
                            ArtystaID = 4
                        },
                        new
                        {
                            PiosenkaID = 16,
                            ArtystaID = 6
                        },
                        new
                        {
                            PiosenkaID = 17,
                            ArtystaID = 6
                        },
                        new
                        {
                            PiosenkaID = 18,
                            ArtystaID = 6
                        },
                        new
                        {
                            PiosenkaID = 18,
                            ArtystaID = 7
                        },
                        new
                        {
                            PiosenkaID = 19,
                            ArtystaID = 6
                        },
                        new
                        {
                            PiosenkaID = 20,
                            ArtystaID = 6
                        },
                        new
                        {
                            PiosenkaID = 21,
                            ArtystaID = 7
                        },
                        new
                        {
                            PiosenkaID = 22,
                            ArtystaID = 7
                        },
                        new
                        {
                            PiosenkaID = 23,
                            ArtystaID = 7
                        },
                        new
                        {
                            PiosenkaID = 24,
                            ArtystaID = 7
                        },
                        new
                        {
                            PiosenkaID = 25,
                            ArtystaID = 7
                        });
                });

            modelBuilder.Entity("DAL.PiosenkaNaCharcie", b =>
                {
                    b.Property<int>("PiosenkaID")
                        .HasColumnType("int");

                    b.Property<int>("ChartPiosenekID")
                        .HasColumnType("int");

                    b.Property<int>("PozycjaPiosenki")
                        .HasColumnType("int");

                    b.HasKey("PiosenkaID", "ChartPiosenekID");

                    b.HasIndex("ChartPiosenekID");

                    b.ToTable("PiosenkaNaCharcie");

                    b.HasData(
                        new
                        {
                            PiosenkaID = 1,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 2,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 3,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 4,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 5,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 6,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 7,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 8,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 9,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 10,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 11,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 12,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 13,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 14,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 15,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 16,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 17,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 18,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 19,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 20,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 21,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 22,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 23,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 24,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 25,
                            ChartPiosenekID = 1,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 16,
                            ChartPiosenekID = 2,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 17,
                            ChartPiosenekID = 2,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 18,
                            ChartPiosenekID = 2,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 19,
                            ChartPiosenekID = 2,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 20,
                            ChartPiosenekID = 2,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 21,
                            ChartPiosenekID = 2,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 22,
                            ChartPiosenekID = 2,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 23,
                            ChartPiosenekID = 2,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 24,
                            ChartPiosenekID = 2,
                            PozycjaPiosenki = 0
                        },
                        new
                        {
                            PiosenkaID = 25,
                            ChartPiosenekID = 2,
                            PozycjaPiosenki = 0
                        });
                });

            modelBuilder.Entity("DAL.Playlista", b =>
                {
                    b.Property<int>("PlaylistaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaylistaID"));

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaylistaID");

                    b.ToTable("Playlista");

                    b.HasData(
                        new
                        {
                            PlaylistaID = 1,
                            Gatunek = "Rap",
                            Nazwa = "Vibe"
                        },
                        new
                        {
                            PlaylistaID = 2,
                            Gatunek = "Rap",
                            Nazwa = "Relax"
                        },
                        new
                        {
                            PlaylistaID = 3,
                            Gatunek = "Rap",
                            Nazwa = "Sunday"
                        },
                        new
                        {
                            PlaylistaID = 4,
                            Gatunek = "Pop",
                            Nazwa = "Girls Night"
                        });
                });

            modelBuilder.Entity("ListaPrzebojow.DAL.AlbumNaCharcie", b =>
                {
                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("ChartAlbumowID")
                        .HasColumnType("int");

                    b.HasKey("AlbumID", "ChartAlbumowID");

                    b.HasIndex("ChartAlbumowID");

                    b.ToTable("AlbumNaCharcie");

                    b.HasData(
                        new
                        {
                            AlbumID = 1,
                            ChartAlbumowID = 1
                        },
                        new
                        {
                            AlbumID = 2,
                            ChartAlbumowID = 1
                        },
                        new
                        {
                            AlbumID = 3,
                            ChartAlbumowID = 1
                        },
                        new
                        {
                            AlbumID = 4,
                            ChartAlbumowID = 1
                        },
                        new
                        {
                            AlbumID = 5,
                            ChartAlbumowID = 1
                        },
                        new
                        {
                            AlbumID = 4,
                            ChartAlbumowID = 2
                        },
                        new
                        {
                            AlbumID = 5,
                            ChartAlbumowID = 2
                        });
                });

            modelBuilder.Entity("ListaPrzebojow.DAL.PiosenkaNaPlayliscie", b =>
                {
                    b.Property<int>("PiosenkaID")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistaID")
                        .HasColumnType("int");

                    b.HasKey("PiosenkaID", "PlaylistaID");

                    b.HasIndex("PlaylistaID");

                    b.ToTable("PiosenkaNaPlayliscie");

                    b.HasData(
                        new
                        {
                            PiosenkaID = 6,
                            PlaylistaID = 1
                        },
                        new
                        {
                            PiosenkaID = 8,
                            PlaylistaID = 1
                        },
                        new
                        {
                            PiosenkaID = 9,
                            PlaylistaID = 1
                        },
                        new
                        {
                            PiosenkaID = 14,
                            PlaylistaID = 1
                        },
                        new
                        {
                            PiosenkaID = 15,
                            PlaylistaID = 1
                        },
                        new
                        {
                            PiosenkaID = 1,
                            PlaylistaID = 2
                        },
                        new
                        {
                            PiosenkaID = 3,
                            PlaylistaID = 2
                        },
                        new
                        {
                            PiosenkaID = 8,
                            PlaylistaID = 2
                        },
                        new
                        {
                            PiosenkaID = 10,
                            PlaylistaID = 2
                        },
                        new
                        {
                            PiosenkaID = 13,
                            PlaylistaID = 2
                        },
                        new
                        {
                            PiosenkaID = 2,
                            PlaylistaID = 3
                        },
                        new
                        {
                            PiosenkaID = 4,
                            PlaylistaID = 3
                        },
                        new
                        {
                            PiosenkaID = 6,
                            PlaylistaID = 3
                        },
                        new
                        {
                            PiosenkaID = 5,
                            PlaylistaID = 3
                        },
                        new
                        {
                            PiosenkaID = 12,
                            PlaylistaID = 3
                        },
                        new
                        {
                            PiosenkaID = 20,
                            PlaylistaID = 4
                        },
                        new
                        {
                            PiosenkaID = 19,
                            PlaylistaID = 4
                        },
                        new
                        {
                            PiosenkaID = 18,
                            PlaylistaID = 4
                        },
                        new
                        {
                            PiosenkaID = 15,
                            PlaylistaID = 4
                        },
                        new
                        {
                            PiosenkaID = 14,
                            PlaylistaID = 4
                        },
                        new
                        {
                            PiosenkaID = 23,
                            PlaylistaID = 4
                        },
                        new
                        {
                            PiosenkaID = 25,
                            PlaylistaID = 4
                        });
                });

            modelBuilder.Entity("DAL.Album", b =>
                {
                    b.HasOne("DAL.ChartAlbumow", null)
                        .WithMany("albumy")
                        .HasForeignKey("ChartAlbumowID");
                });

            modelBuilder.Entity("DAL.ArtystaAlbum", b =>
                {
                    b.HasOne("DAL.Album", "album")
                        .WithMany("artystaAlbumCol")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Artysta", "artysta")
                        .WithMany("artystaAlbumCol")
                        .HasForeignKey("ArtystaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("album");

                    b.Navigation("artysta");
                });

            modelBuilder.Entity("DAL.ChartAlbumow", b =>
                {
                    b.HasOne("DAL.Chart", "chart")
                        .WithOne("chartAlbumow")
                        .HasForeignKey("DAL.ChartAlbumow", "ChartAlbumowID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("chart");
                });

            modelBuilder.Entity("DAL.ChartPiosenek", b =>
                {
                    b.HasOne("DAL.Chart", "chart")
                        .WithOne("chartPiosenek")
                        .HasForeignKey("DAL.ChartPiosenek", "ChartPiosenekID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("chart");
                });

            modelBuilder.Entity("DAL.Piosenka", b =>
                {
                    b.HasOne("DAL.Album", "album")
                        .WithMany("piosenkaCol")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.ChartPiosenek", null)
                        .WithMany("piosenki")
                        .HasForeignKey("ChartPiosenekID");

                    b.HasOne("DAL.Playlista", null)
                        .WithMany("piosenkaCol")
                        .HasForeignKey("PlaylistaID");

                    b.Navigation("album");
                });

            modelBuilder.Entity("DAL.PiosenkaArtysta", b =>
                {
                    b.HasOne("DAL.Artysta", "artysta")
                        .WithMany("piosenkaArtystaCol")
                        .HasForeignKey("ArtystaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Piosenka", "piosenka")
                        .WithMany("piosenkaArtystaCol")
                        .HasForeignKey("PiosenkaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("artysta");

                    b.Navigation("piosenka");
                });

            modelBuilder.Entity("DAL.PiosenkaNaCharcie", b =>
                {
                    b.HasOne("DAL.ChartPiosenek", "chartPiosenek")
                        .WithMany("PiosenkaNaCharcieCol")
                        .HasForeignKey("ChartPiosenekID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Piosenka", "piosenka")
                        .WithMany("PiosenkaNaCharcieCol")
                        .HasForeignKey("PiosenkaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("chartPiosenek");

                    b.Navigation("piosenka");
                });

            modelBuilder.Entity("ListaPrzebojow.DAL.AlbumNaCharcie", b =>
                {
                    b.HasOne("DAL.Album", "album")
                        .WithMany("AlbumNaCharcieCol")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.ChartAlbumow", "chartAlbumow")
                        .WithMany("AlbumNaCharcieCol")
                        .HasForeignKey("ChartAlbumowID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("album");

                    b.Navigation("chartAlbumow");
                });

            modelBuilder.Entity("ListaPrzebojow.DAL.PiosenkaNaPlayliscie", b =>
                {
                    b.HasOne("DAL.Piosenka", "piosenka")
                        .WithMany("PiosenkaNaPlayliscieCol")
                        .HasForeignKey("PiosenkaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Playlista", "playlista")
                        .WithMany("PiosenkaNaPlayliscieCol")
                        .HasForeignKey("PlaylistaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("piosenka");

                    b.Navigation("playlista");
                });

            modelBuilder.Entity("DAL.Album", b =>
                {
                    b.Navigation("AlbumNaCharcieCol");

                    b.Navigation("artystaAlbumCol");

                    b.Navigation("piosenkaCol");
                });

            modelBuilder.Entity("DAL.Artysta", b =>
                {
                    b.Navigation("artystaAlbumCol");

                    b.Navigation("piosenkaArtystaCol");
                });

            modelBuilder.Entity("DAL.Chart", b =>
                {
                    b.Navigation("chartAlbumow")
                        .IsRequired();

                    b.Navigation("chartPiosenek")
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.ChartAlbumow", b =>
                {
                    b.Navigation("AlbumNaCharcieCol");

                    b.Navigation("albumy");
                });

            modelBuilder.Entity("DAL.ChartPiosenek", b =>
                {
                    b.Navigation("PiosenkaNaCharcieCol");

                    b.Navigation("piosenki");
                });

            modelBuilder.Entity("DAL.Piosenka", b =>
                {
                    b.Navigation("PiosenkaNaCharcieCol");

                    b.Navigation("PiosenkaNaPlayliscieCol");

                    b.Navigation("piosenkaArtystaCol");
                });

            modelBuilder.Entity("DAL.Playlista", b =>
                {
                    b.Navigation("PiosenkaNaPlayliscieCol");

                    b.Navigation("piosenkaCol");
                });
#pragma warning restore 612, 618
        }
    }
}
